---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trader-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trader-service
  template:
    metadata:
      labels:
        app: trader-service
    spec:
      containers:
      - name: hello
        image: nginxdemos/trader-service
        ports:
        - containerPort: 8080
